### ISSUE TITLE
espec 1.8.2 fails to compile in elixir 1.11.0

### ISSUE THREAD

**Issue by sampscl** [antonmi/espec#301]
When compiling, I get the following:
> == Compilation error in file lib/mix/utils/stale_compatible.ex ==
> ** (ArgumentError) record :source does not have the key: :struct_references
>     (elixir 1.11.0) lib/record.ex:420: Record.create/4
>     (mix 1.11.0) expanding macro: Mix.Compilers.Elixir.source/1
>     lib/mix/utils/stale_compatible.ex:230: Mix.Utils.StaleCompatible.dependent_modules/4
> could not compile dependency :espec, "mix compile" failed. You can recompile this dependency with "mix deps.compile espec", > update it with "mix deps.update espec" or clean it with "mix deps.clean espec"

**Comment by antonmi** [comment]
Hey @sampscl !
It is fixed in 1.8.3.
Thank you for using ESpec!
